<#
.SYNOPSIS
Creates JSON and Markdown summaries from project health evidence files.
.DESCRIPTION
Reads evidence JSON files generated by project health checks, summarizes classifications, writes compact reports, and appends the Markdown report to the GitHub Actions job summary when available.
#>
param(
    [Parameter(Mandatory = $false)]
    [string]$EvidenceDirectory = "evidence",

    [Parameter(Mandatory = $false)]
    [string]$OutputDirectory = "evidence-summary",

    [Parameter(Mandatory = $false)]
    [string]$Prefix = "project-health-summary"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

$items = @()
if (Test-Path $EvidenceDirectory) {
    $files = Get-ChildItem -Path $EvidenceDirectory -Filter "*.json" -File | Sort-Object Name
}
else {
    $files = @()
}

foreach ($file in $files) {
    try {
        $json = Get-Content -Path $file.FullName -Raw | ConvertFrom-Json
        $items += [pscustomobject]@{
            file = $file.Name
            project = $json.project
            check_mode = $json.check_mode
            host = $json.host
            resolved_url = $json.resolved_url
            classification = $json.classification
            http_status = $json.http_status
            manual_review_required = $json.manual_review_required
            strict_failure = $json.strict_failure
            error_summary = $json.error_summary
        }
    }
    catch {
        $items += [pscustomobject]@{
            file = $file.Name
            project = "unknown"
            check_mode = "unknown"
            host = "unknown"
            resolved_url = "unknown"
            classification = "parse_error"
            http_status = $null
            manual_review_required = $true
            strict_failure = $true
            error_summary = $_.Exception.Message
        }
    }
}

$healthy = @($items | Where-Object { $_.classification -eq "healthy" })
$needsReview = @($items | Where-Object { $_.classification -ne "healthy" })
$overallClassification = if ($items.Count -eq 0) { "no_evidence" } elseif ($needsReview.Count -eq 0) { "healthy" } else { "manual_review_required" }

$timestamp = (Get-Date).ToUniversalTime().ToString("yyyyMMdd-HHmmss")
$jsonPath = Join-Path $OutputDirectory "$Prefix-$timestamp.json"
$mdPath = Join-Path $OutputDirectory "$Prefix-$timestamp.md"

$summary = [ordered]@{
    schema_version = "1.0"
    generated_utc = (Get-Date).ToUniversalTime().ToString("o")
    evidence_directory = $EvidenceDirectory
    total_items = $items.Count
    healthy_count = $healthy.Count
    review_count = $needsReview.Count
    overall_classification = $overallClassification
    items = $items
}

$summary | ConvertTo-Json -Depth 8 | Set-Content -Path $jsonPath -Encoding UTF8

$lines = @()
$lines += "# Project Health Evidence Summary"
$lines += ""
$lines += "Generated UTC: $($summary.generated_utc)"
$lines += ""
$lines += "| Metric | Value |"
$lines += "|---|---:|"
$lines += "| Total evidence files | $($summary.total_items) |"
$lines += "| Healthy | $($summary.healthy_count) |"
$lines += "| Review required | $($summary.review_count) |"
$lines += "| Overall classification | $($summary.overall_classification) |"
$lines += ""
$lines += "| Project | Mode | Classification | HTTP | Host | Review |"
$lines += "|---|---|---|---:|---|---:|"
if ($items.Count -eq 0) {
    $lines += "| none | none | no_evidence |  |  | True |"
}
else {
    foreach ($item in $items) {
        $lines += "| $($item.project) | $($item.check_mode) | $($item.classification) | $($item.http_status) | $($item.host) | $($item.manual_review_required) |"
    }
}

$lines | Set-Content -Path $mdPath -Encoding UTF8

if (-not [string]::IsNullOrWhiteSpace($env:GITHUB_STEP_SUMMARY)) {
    $lines | Add-Content -Path $env:GITHUB_STEP_SUMMARY -Encoding UTF8
}

Write-Host "Summary JSON: $jsonPath"
Write-Host "Summary Markdown: $mdPath"
Write-Host "Overall classification: $($summary.overall_classification)"

[pscustomobject]@{
    JsonPath = $jsonPath
    MarkdownPath = $mdPath
    OverallClassification = $summary.overall_classification
    TotalItems = $summary.total_items
    HealthyCount = $summary.healthy_count
    ReviewCount = $summary.review_count
}
